/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import models.tables.Users;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record11<String, String, Boolean, String, String, LocalDateTime, String, String, String, String, String> {

    private static final long serialVersionUID = -2036643405;

    /**
     * Setter for <code>public.users.login</code>.
     */
    public void setLogin(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.login</code>.
     */
    public String getLogin() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.users.droit</code>.
     */
    public void setDroit(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.droit</code>.
     */
    public String getDroit() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.etat</code>.
     */
    public void setEtat(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.etat</code>.
     */
    public Boolean getEtat() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.users.passe</code>.
     */
    public void setPasse(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.passe</code>.
     */
    public String getPasse() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.who_done</code>.
     */
    public void setWhoDone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.who_done</code>.
     */
    public String getWhoDone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.when_done</code>.
     */
    public void setWhenDone(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.when_done</code>.
     */
    public LocalDateTime getWhenDone() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.users.nom_prenom</code>.
     */
    public void setNomPrenom(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.nom_prenom</code>.
     */
    public String getNomPrenom() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.photo</code>.
     */
    public void setPhoto(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.photo</code>.
     */
    public String getPhoto() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.users.batiment</code>.
     */
    public void setBatiment(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.batiment</code>.
     */
    public String getBatiment() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.users.niveau</code>.
     */
    public void setNiveau(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.users.niveau</code>.
     */
    public String getNiveau() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.users.porte</code>.
     */
    public void setPorte(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.users.porte</code>.
     */
    public String getPorte() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, Boolean, String, String, LocalDateTime, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, Boolean, String, String, LocalDateTime, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Users.USERS.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.DROIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return Users.USERS.ETAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Users.USERS.PASSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Users.USERS.WHO_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return Users.USERS.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Users.USERS.NOM_PRENOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Users.USERS.PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Users.USERS.BATIMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Users.USERS.NIVEAU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Users.USERS.PORTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDroit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getEtat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPasse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNomPrenom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getBatiment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getPorte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDroit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getEtat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPasse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWhoDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNomPrenom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getBatiment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getPorte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(String value) {
        setLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setDroit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(Boolean value) {
        setEtat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(String value) {
        setPasse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(String value) {
        setWhoDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value6(LocalDateTime value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value7(String value) {
        setNomPrenom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value8(String value) {
        setPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value9(String value) {
        setBatiment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value10(String value) {
        setNiveau(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value11(String value) {
        setPorte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(String value1, String value2, Boolean value3, String value4, String value5, LocalDateTime value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String login, String droit, Boolean etat, String passe, String whoDone, LocalDateTime whenDone, String nomPrenom, String photo, String batiment, String niveau, String porte) {
        super(Users.USERS);

        set(0, login);
        set(1, droit);
        set(2, etat);
        set(3, passe);
        set(4, whoDone);
        set(5, whenDone);
        set(6, nomPrenom);
        set(7, photo);
        set(8, batiment);
        set(9, niveau);
        set(10, porte);
    }
}
