/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import models.tables.VAssistance;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAssistanceRecord extends TableRecordImpl<VAssistanceRecord> implements Record16<Long, String, String, String, Boolean, String, LocalDateTime, LocalDateTime, String, String, String, String, Boolean, Boolean, LocalDateTime, String> {

    private static final long serialVersionUID = 2097357464;

    /**
     * Setter for <code>public.v_assistance.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_assistance.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.v_assistance.motif</code>.
     */
    public void setMotif(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_assistance.motif</code>.
     */
    public String getMotif() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_assistance.declarant</code>.
     */
    public void setDeclarant(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_assistance.declarant</code>.
     */
    public String getDeclarant() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.v_assistance.observations</code>.
     */
    public void setObservations(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_assistance.observations</code>.
     */
    public String getObservations() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.v_assistance.is_close</code>.
     */
    public void setIsClose(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_assistance.is_close</code>.
     */
    public Boolean getIsClose() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.v_assistance.maintenacier</code>.
     */
    public void setMaintenacier(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_assistance.maintenacier</code>.
     */
    public String getMaintenacier() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_assistance.when_done</code>.
     */
    public void setWhenDone(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_assistance.when_done</code>.
     */
    public LocalDateTime getWhenDone() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.v_assistance.when_close</code>.
     */
    public void setWhenClose(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_assistance.when_close</code>.
     */
    public LocalDateTime getWhenClose() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.v_assistance.nom_prenom</code>.
     */
    public void setNomPrenom(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_assistance.nom_prenom</code>.
     */
    public String getNomPrenom() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.v_assistance.batiment</code>.
     */
    public void setBatiment(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.v_assistance.batiment</code>.
     */
    public String getBatiment() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.v_assistance.niveau</code>.
     */
    public void setNiveau(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.v_assistance.niveau</code>.
     */
    public String getNiveau() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.v_assistance.porte</code>.
     */
    public void setPorte(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.v_assistance.porte</code>.
     */
    public String getPorte() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.v_assistance.is_ok</code>.
     */
    public void setIsOk(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.v_assistance.is_ok</code>.
     */
    public Boolean getIsOk() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.v_assistance.new_create</code>.
     */
    public void setNewCreate(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.v_assistance.new_create</code>.
     */
    public Boolean getNewCreate() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.v_assistance.when_ok</code>.
     */
    public void setWhenOk(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.v_assistance.when_ok</code>.
     */
    public LocalDateTime getWhenOk() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.v_assistance.direction</code>.
     */
    public void setDirection(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.v_assistance.direction</code>.
     */
    public String getDirection() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, String, String, Boolean, String, LocalDateTime, LocalDateTime, String, String, String, String, Boolean, Boolean, LocalDateTime, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, String, String, Boolean, String, LocalDateTime, LocalDateTime, String, String, String, String, Boolean, Boolean, LocalDateTime, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VAssistance.V_ASSISTANCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VAssistance.V_ASSISTANCE.MOTIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VAssistance.V_ASSISTANCE.DECLARANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VAssistance.V_ASSISTANCE.OBSERVATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return VAssistance.V_ASSISTANCE.IS_CLOSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return VAssistance.V_ASSISTANCE.MAINTENACIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return VAssistance.V_ASSISTANCE.WHEN_DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return VAssistance.V_ASSISTANCE.WHEN_CLOSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return VAssistance.V_ASSISTANCE.NOM_PRENOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return VAssistance.V_ASSISTANCE.BATIMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return VAssistance.V_ASSISTANCE.NIVEAU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return VAssistance.V_ASSISTANCE.PORTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return VAssistance.V_ASSISTANCE.IS_OK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return VAssistance.V_ASSISTANCE.NEW_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field15() {
        return VAssistance.V_ASSISTANCE.WHEN_OK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return VAssistance.V_ASSISTANCE.DIRECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMotif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDeclarant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getObservations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getIsClose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMaintenacier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getWhenClose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getNomPrenom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getBatiment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getPorte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component13() {
        return getIsOk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getNewCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component15() {
        return getWhenOk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMotif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDeclarant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getObservations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getIsClose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMaintenacier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getWhenDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getWhenClose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getNomPrenom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getBatiment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getPorte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getIsOk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getNewCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value15() {
        return getWhenOk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value2(String value) {
        setMotif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value3(String value) {
        setDeclarant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value4(String value) {
        setObservations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value5(Boolean value) {
        setIsClose(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value6(String value) {
        setMaintenacier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value7(LocalDateTime value) {
        setWhenDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value8(LocalDateTime value) {
        setWhenClose(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value9(String value) {
        setNomPrenom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value10(String value) {
        setBatiment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value11(String value) {
        setNiveau(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value12(String value) {
        setPorte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value13(Boolean value) {
        setIsOk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value14(Boolean value) {
        setNewCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value15(LocalDateTime value) {
        setWhenOk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord value16(String value) {
        setDirection(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VAssistanceRecord values(Long value1, String value2, String value3, String value4, Boolean value5, String value6, LocalDateTime value7, LocalDateTime value8, String value9, String value10, String value11, String value12, Boolean value13, Boolean value14, LocalDateTime value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VAssistanceRecord
     */
    public VAssistanceRecord() {
        super(VAssistance.V_ASSISTANCE);
    }

    /**
     * Create a detached, initialised VAssistanceRecord
     */
    public VAssistanceRecord(Long id, String motif, String declarant, String observations, Boolean isClose, String maintenacier, LocalDateTime whenDone, LocalDateTime whenClose, String nomPrenom, String batiment, String niveau, String porte, Boolean isOk, Boolean newCreate, LocalDateTime whenOk, String direction) {
        super(VAssistance.V_ASSISTANCE);

        set(0, id);
        set(1, motif);
        set(2, declarant);
        set(3, observations);
        set(4, isClose);
        set(5, maintenacier);
        set(6, whenDone);
        set(7, whenClose);
        set(8, nomPrenom);
        set(9, batiment);
        set(10, niveau);
        set(11, porte);
        set(12, isOk);
        set(13, newCreate);
        set(14, whenOk);
        set(15, direction);
    }
}
