/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 878327733;

    private String        login;
    private String        droit;
    private Boolean       etat;
    private String        passe;
    private String        whoDone;
    private LocalDateTime whenDone;
    private String        nomPrenom;
    private String        photo;
    private Integer       telephone;

    public Users() {}

    public Users(Users value) {
        this.login = value.login;
        this.droit = value.droit;
        this.etat = value.etat;
        this.passe = value.passe;
        this.whoDone = value.whoDone;
        this.whenDone = value.whenDone;
        this.nomPrenom = value.nomPrenom;
        this.photo = value.photo;
        this.telephone = value.telephone;
    }

    public Users(
        String        login,
        String        droit,
        Boolean       etat,
        String        passe,
        String        whoDone,
        LocalDateTime whenDone,
        String        nomPrenom,
        String        photo,
        Integer       telephone
    ) {
        this.login = login;
        this.droit = droit;
        this.etat = etat;
        this.passe = passe;
        this.whoDone = whoDone;
        this.whenDone = whenDone;
        this.nomPrenom = nomPrenom;
        this.photo = photo;
        this.telephone = telephone;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getDroit() {
        return this.droit;
    }

    public void setDroit(String droit) {
        this.droit = droit;
    }

    public Boolean getEtat() {
        return this.etat;
    }

    public void setEtat(Boolean etat) {
        this.etat = etat;
    }

    public String getPasse() {
        return this.passe;
    }

    public void setPasse(String passe) {
        this.passe = passe;
    }

    public String getWhoDone() {
        return this.whoDone;
    }

    public void setWhoDone(String whoDone) {
        this.whoDone = whoDone;
    }

    public LocalDateTime getWhenDone() {
        return this.whenDone;
    }

    public void setWhenDone(LocalDateTime whenDone) {
        this.whenDone = whenDone;
    }

    public String getNomPrenom() {
        return this.nomPrenom;
    }

    public void setNomPrenom(String nomPrenom) {
        this.nomPrenom = nomPrenom;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Integer getTelephone() {
        return this.telephone;
    }

    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(login);
        sb.append(", ").append(droit);
        sb.append(", ").append(etat);
        sb.append(", ").append(passe);
        sb.append(", ").append(whoDone);
        sb.append(", ").append(whenDone);
        sb.append(", ").append(nomPrenom);
        sb.append(", ").append(photo);
        sb.append(", ").append(telephone);

        sb.append(")");
        return sb.toString();
    }
}
