/*
 * This file is generated by jOOQ.
*/
package models;


import javax.annotation.Generated;

import models.tables.Assistance;
import models.tables.Users;
import models.tables.records.AssistanceRecord;
import models.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AssistanceRecord, Long> IDENTITY_ASSISTANCE = Identities0.IDENTITY_ASSISTANCE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AssistanceRecord> ASSISTANCE_PKEY = UniqueKeys0.ASSISTANCE_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AssistanceRecord, UsersRecord> ASSISTANCE__ASSISTANCE_DECLARANT_FKEY = ForeignKeys0.ASSISTANCE__ASSISTANCE_DECLARANT_FKEY;
    public static final ForeignKey<AssistanceRecord, UsersRecord> ASSISTANCE__ASSISTANCE_MAINTENACIER_FKEY = ForeignKeys0.ASSISTANCE__ASSISTANCE_MAINTENACIER_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AssistanceRecord, Long> IDENTITY_ASSISTANCE = createIdentity(Assistance.ASSISTANCE, Assistance.ASSISTANCE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AssistanceRecord> ASSISTANCE_PKEY = createUniqueKey(Assistance.ASSISTANCE, "assistance_pkey", Assistance.ASSISTANCE.ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = createUniqueKey(Users.USERS, "users_pkey", Users.USERS.LOGIN);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AssistanceRecord, UsersRecord> ASSISTANCE__ASSISTANCE_DECLARANT_FKEY = createForeignKey(models.Keys.USERS_PKEY, Assistance.ASSISTANCE, "assistance__assistance_declarant_fkey", Assistance.ASSISTANCE.DECLARANT);
        public static final ForeignKey<AssistanceRecord, UsersRecord> ASSISTANCE__ASSISTANCE_MAINTENACIER_FKEY = createForeignKey(models.Keys.USERS_PKEY, Assistance.ASSISTANCE, "assistance__assistance_maintenacier_fkey", Assistance.ASSISTANCE.MAINTENACIER);
    }
}
