/*
 * This file is generated by jOOQ.
*/
package models;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Assistance;
import models.tables.Users;
import models.tables.VAssistance;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 408426070;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.assistance</code>.
     */
    public final Assistance ASSISTANCE = models.tables.Assistance.ASSISTANCE;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = models.tables.Users.USERS;

    /**
     * The table <code>public.v_assistance</code>.
     */
    public final VAssistance V_ASSISTANCE = models.tables.VAssistance.V_ASSISTANCE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ASSISTANCE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Assistance.ASSISTANCE,
            Users.USERS,
            VAssistance.V_ASSISTANCE);
    }
}
